### ISSUE TITLE
Look this code please

### ISSUE THREAD

**Issue by Naxtrico** [Naxtrico/relaciones#2]
No sería mejor llamar a section con una clase "content_color" y quitar el div contenedor?
Al intentar poner un padding top en el div content color no me hacía nada porque hay un section sectionsPF que no hace nada, si no dar espacio entre el section de arriba y el div de abajo. Eso es raro.

SUGERENCIA

```
<section class="content_color">
   <h2>SELECCIONA UN TEMA PARA LA PRUEBA DE FIDELIDAD</h2>
   <p>Un tema es el hilo conductor de nuestra prueba de fidelidad, marcará el lugar, el personaje</p>
    <p>que interpretará nuestro actor/iz y los hechos que pasarán. Mira nuestros temas y elige el</p>
    <p>que creas que más se pueda adaptar a la manera de ser de tu pareja.</p>
</section>
```

CÓDIGO ACTUAL

```
<div  class="content_color">
<section class="sectionsPF" id="products">
   <h2>SELECCIONA UN TEMA PARA LA PRUEBA DE FIDELIDAD</h2>
   <p>Un tema es el hilo conductor de nuestra prueba de fidelidad, marcará el lugar, el personaje</p>
    <p>que interpretará nuestro actor/iz y los hechos que pasarán. Mira nuestros temas y elige el</p>
    <p>que creas que más se pueda adaptar a la manera de ser de tu pareja.</p>
<div class="card">
```

**Comment by davecarter** [comment]
:+1:  agree

**Comment by JORDICUTILLAS** [comment]
el porque de crear un div con content color, es porque el section class="sectionsPF" tiene un with que contiene el contenido del section que comparten todos los sections. Al aver cambio de color de fondo en algunos de ellos, se me ocurrió crear un div 100%.
